{{- range .Values.traefik.routes }}
{{- if .htaccess }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-auth" $.Values.name }}
  namespace: {{ $.Release.Namespace }}
data:
  users: {{ range .htaccess.users }}{{ printf "%s:%s\n" .username .password | b64enc }}{{ end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-auth" $.Values.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  basicAuth:
    secret: {{ printf "%s-auth" $.Values.name }}
{{- end }}
{{- end }}
