{{- if eq .Values.database.type "mysql" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databases.fullname" . }}-mysql-secret
  labels:
    {{- include "databases.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootUser: {{ .Values.mysql.credentials.rootUser | quote }}
  rootHost: "%"
  rootPassword: {{ .Values.mysql.credentials.rootPassword | quote }}
{{- end }}
