{{- if eq .Values.database.type "mysql" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "databases.fullname" . }}-mysql-sa
  labels:
    {{- include "databases.labels" . | nindent 4 }}
{{- end }}
