{{- if eq .Values.database.type "redis" }}
{{- if .Values.redis.redisSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.redisSecret.name }}
  labels:
    {{- include "databases.labels" . | nindent 4 }}
type: Opaque
data:
  redisPassword: {{ .Values.redis.redisPassword | b64enc }}
{{- end }}
{{- end }}
