{{- if eq .Values.database.type "mariadb" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.rootPasswordSecretName }}
  labels:
    {{- include "databases.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.mariadb.rootPassword | b64enc }}
{{- range .Values.mariadb.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .passwordSecretName }}
  labels:
    app: {{ include "databases.fullname" $ }}
type: Opaque
data:
  password: {{ .password | b64enc }}
{{- end }}
{{- end }}
