{{- if eq .Values.database.type "postgres" }}
{{- $pg := .Values.postgres }}
{{- if $pg.initdb.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pg.initdb.passwordSecretName }}
  labels:
    {{- include "databases.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $pg.initdb.user | quote }}
  password: {{ $pg.initdb.password | quote }}
{{- end }}
{{- if $pg.initdb.passwordSuperUser }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databases.fullname" . }}-postgres-superuser
  labels:
    {{- include "databases.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "postgres"
  password: {{ $pg.initdb.passwordSuperUser | quote }}
{{- end }}
{{- end }}
